name: 'Setup Python'
description: 'Setup Python with caching'
inputs:
  python_version:
    description: 'Python version'
    required: false
    default: '3.13'
  cache_dependency_paths:
    description: 'Glob pattern for dependency files for caching (e.g., **/requirements*.txt or pyproject.toml)'
    required: false
    default: '**/requirements*.txt'
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.cache_dependency_paths }}
    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip
